### PR TITLE
feat: Add Apigateway related permissions

### PR DESCRIPTION
**Pull request by ramgudivada-lacework**
## Summary
Add Apigateway permissions for read operations that are called during RM collections

## How did you test this change?
- unit tests
- testing in dev8

## Issue
https://lacework.atlassian.net/browse/RAIN-65489

### CODE REVIEW

**Review by afiune — APPROVED** [review]

**Comment by abhiram-m-kaushik-lw** [comment]
What about `apigateway:List*` ?

**Comment by afiune** [comment]
@abhiram-m-kaushik-lw Tests are running in codefresh. 

Screenshot 2023-07-18 at 4 28 19 PM

**Comment by afiune** [comment]
To keep in mind, these tests are not end-to-end tests. These are just tests that verify we will deploy what ever we are deploying correctly.

**Comment by abhiram-m-kaushik-lw** [comment]
> To keep in mind, these tests are not end-to-end tests. These are just tests that verify we will deploy what ever we are deploying correctly.

Understood, thanks.

**Comment by ramgudivada-lacework** [comment]
> 1. What about `apigateway:List*` ?
> 2. Where can I find the unit tests?

There are no List* calls for this service. 
Unit tests are run as part of CF pipelines.

**Review by abhiram-m-kaushik-lw — APPROVED** [review]

**Pull request merged**
