### PR TITLE
fix: add tags to IAM Policy

### PR DESCRIPTION
**Pull request by rajgandhi9**
***Issue***: Add tags to IAM Policy

***Description:***
Adding the user provided tags to the IAM policy created by this terraform module

***Additional Info:***
N/A

### CODE REVIEW

**Comment by afiune** [comment]
MAKE IT SO! 🎉

@rajgandhi9 Thank you so much for your contribution! 

In order to accept this PR, we need you to sign your commits for security reasons. This is part of our development and contributing guidelines: https://github.com/lacework/terraform-aws-config/blob/main/DEVELOPER_GUIDELINES.md#signing-commits

**Comment by rajgandhi9** [comment]
@afiune - Signed the commit. Thanks.

**Comment by afiune** [comment]
make it so

**Comment by rajgandhi9** [comment]
@afiune - Anything else required from my side? Thanks.

**Comment by rajgandhi9** [comment]
@afiune - Thank you. Will you be releasing a new version with these changes?

**Pull request merged**
